### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hawkeyexp** [raspberrypi-ui/plymouth#2]
Sorry to ask here but didn't found good infos about.
I wan't to create a customized mod of the tribar theme whitch changed colors and possible a bg image.
Is there an guide etc. or can you give some samples how it can be done ?
Thx

**Comment by spl237** [comment]
I'm sorry - I don't have the time to deal with questions of this nature. Please ask on the Pi forums - someone on there may be able to help you.
